name: Build
on:
    pull_request: {}
    merge_group:
        types: [checks_requested]
    push: {}
jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ linux, darwin, windows, freebsd, netbsd, openbsd ]
        arch: [ amd64, arm64 ]
        go-version: [ 1.20 ]
        include:
          - os: linux
            arch: arm
          - os: freebsd
            arch: arm
          - os: netbsd
            arch: arm
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Setup Golang
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - run: go build -o build/powerline-go-$GOOS-$GOARCH
        env:
          CGO_ENABLED: 0
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
      - if: matrix.os == 'linux' && matrix.arch == 'amd64'
        run: build/powerline-go-linux-amd64 --help
